//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCapInsetsPlugin\src\main\java\com\ashera\capinsets\CapInsetsViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CapInsetsViewImpl")
#ifdef RESTRICT_CapInsetsViewImpl
#define INCLUDE_ALL_CapInsetsViewImpl 0
#else
#define INCLUDE_ALL_CapInsetsViewImpl 1
#endif
#undef RESTRICT_CapInsetsViewImpl

#if !defined (ASCapInsetsViewImpl_) && (INCLUDE_ALL_CapInsetsViewImpl || defined(INCLUDE_ASCapInsetsViewImpl))
#define ASCapInsetsViewImpl_

#define RESTRICT_IAttributable 1
#define INCLUDE_ASIAttributable 1
#include "IAttributable.h"

@class ASWidgetAttribute;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;

@interface ASCapInsetsViewImpl : NSObject < ASIAttributable >

#pragma mark Public

- (instancetype)init;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (NSString *)getLocalName;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCapInsetsViewImpl)

inline NSString *ASCapInsetsViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCapInsetsViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCapInsetsViewImpl, LOCAL_NAME, NSString *)

FOUNDATION_EXPORT void ASCapInsetsViewImpl_init(ASCapInsetsViewImpl *self);

FOUNDATION_EXPORT ASCapInsetsViewImpl *new_ASCapInsetsViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCapInsetsViewImpl *create_ASCapInsetsViewImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCapInsetsViewImpl)

@compatibility_alias ComAsheraCapinsetsCapInsetsViewImpl ASCapInsetsViewImpl;

#endif

#pragma pop_macro("INCLUDE_ALL_CapInsetsViewImpl")
